plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':module-common:core')
    implementation project(':module-common:web')
    implementation project(':module-common:security')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    runtimeOnly 'com.mysql:mysql-connector-j'
}
